version: '3'
services:
  monolith:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: ${GOPROXY}
        BIN: monolith
    ports:
      - "8090:8080"
    environment:
      - SHOP_MONOLITH_BIND_ADDR=:8080

  orders:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: ${GOPROXY}
        BIN: microservices/orders
    ports:
      - "8070:8080"
    environment:
      - SHOP_ORDERS_SERVICE_BIND_ADDR=:8080
      - SHOP_RABBITMQ_ADDR=rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE=orders-to-pay
      - SHOP_SHOP_SERVICE_ADDR=http://shop:8080
    depends_on:
      - rabbitmq

  payments:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: ${GOPROXY}
        BIN: microservices/payments
    environment:
      - SHOP_RABBITMQ_ADDR=rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE=orders-to-pay
      - SHOP_ORDERS_SERVICE_ADDR=http://orders:8080
    depends_on:
      - rabbitmq

  shop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: ${GOPROXY}
        BIN: microservices/shop
    environment:
      - SHOP_SHOP_SERVICE_BIND_ADDR=:8080
    ports:
      - "8071:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"

#  tests:
#    build:
#      context: .
#      dockerfile_inline: |
#        FROM golang:1.21.0
#        WORKDIR $GO_PROJECT_DIR
#        ENV GOPROXY=$GOPROXY
#    entrypoint: [ "sleep", "infinity" ]
#    depends_on:
#      - shop
#      - payments
#      - orders
#      - monolith
#    volumes:
#      - .:$GO_PROJECT_DIR
